CREATE TABLE users (
    user_id int IDENTITY(1,1) PRIMARY KEY,
    username NVARCHAR(50) NOT NULL,
    email NVARCHAR(320) NOT NULL,
    mobile_number NVARCHAR(20) NULL,
    password_hash NVARCHAR(255) NULL,
    first_name NVARCHAR(50) NOT NULL,
    last_name NVARCHAR(50) NOT NULL,
    birth_date DATE NULL,
    gender_preference NVARCHAR(20) NULL,
    about_me NVARCHAR(500) NULL,
    city_id int not null References 
    works_at NVARCHAR(200) NULL,
    studied_at NVARCHAR(200) NULL,
    relationship_status NVARCHAR(20) DEFAULT 'not_specified' NOT NULL,
    profile_photo_url NVARCHAR(500) NULL,
    is_verified BIT DEFAULT 0 NOT NULL,
    is_active BIT DEFAULT 1 NOT NULL,
    profile_completed BIT DEFAULT 0 NOT NULL,
    email_confirmed BIT DEFAULT 0 NOT NULL,
    mobile_confirmed BIT DEFAULT 0 NOT NULL,
    account_privacy NVARCHAR(10) DEFAULT 'public' NOT NULL,
    created_date DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
    last_updated DATETIME2 DEFAULT GETUTCDATE() NOT NULL,
    CONSTRAINT UQ_users_username UNIQUE (username),
    CONSTRAINT UQ_users_email UNIQUE (email),
    CONSTRAINT CK_users_username_length CHECK (LEN(username) >= 3 AND LEN(username) <= 50),
    CONSTRAINT CK_users_username_format CHECK (username NOT LIKE '%[^a-zA-Z0-9._]%'),
    CONSTRAINT CK_users_email_basic CHECK (email LIKE '%@%.%'),
    CONSTRAINT CK_users_names_not_empty CHECK (LEN(TRIM(first_name)) > 0 AND LEN(TRIM(last_name)) > 0),
    CONSTRAINT CK_users_birth_date CHECK (birth_date IS NULL OR birth_date <= GETDATE()),
    CONSTRAINT CK_users_age_limit CHECK (birth_date IS NULL OR (DATEDIFF(Month, birth_date, GETDATE())/12.0) >= 13),
    CONSTRAINT CK_users_gender CHECK (gender_preference IS NULL OR gender_preference IN ('male', 'female', 'prefer_not_to_say')),
    CONSTRAINT CK_users_relationship CHECK (relationship_status IN ('single', 'in_relationship', 'married', 'not_specified')),
    CONSTRAINT CK_users_privacy CHECK (account_privacy IN ('public', 'friends', 'private')),
    CONSTRAINT CK_users_about_length CHECK (about_me IS NULL OR LEN(about_me) <= 500),
    CONSTRAINT CK_users_studied_at_length CHECK (studied_at IS NULL OR LEN(studied_at) <= 200),
    CONSTRAINT CK_users_works_at_length CHECK (works_at IS NULL OR LEN(works_at) <= 200),
    CONSTRAINT CK_users_contact_required CHECK (email IS NOT NULL OR mobile_number IS NOT NULL),
    CONSTRAINT CK_users_auth_method CHECK (password_hash IS NOT NULL OR email_confirmed = 1)
);
CREATE NONCLUSTERED INDEX IX_users_username ON users (username);
